version: '3'

services:
  minio:
    image: quay.io/minio/minio
    volumes:
      - ./minio/data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin'
      MINIO_ADDRESS: ':9000'
      MINIO_STORAGE_USE_HTTPS: False
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data

  api:
    build: .
    container_name: fastapi_server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin'
      MINIO_ACCESS_KEY: minioadmin  # Required for StreamingDataset (S3-compatible)
      MINIO_SECRET_KEY: minioadmin  # Required for StreamingDataset (S3-compatible)
      AWS_ACCESS_KEY_ID: minioadmin  # Required for StreamingDataset (S3-compatible)
      AWS_SECRET_ACCESS_KEY: minioadmin  # Required for StreamingDataset (S3-compatible)
      S3_ENDPOINT_URL: http://minio:9000  # S3-compatible endpoint
    command: uvicorn api.api_server:app --host 0.0.0.0 --port 8000
