version: '3.8'

services:
  app:
    build: .
    container_name: vector_db_app
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - .:/app
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    networks:
      - app_network

  qdrant:
    image: qdrant/qdrant:v1.1.2
    container_name: qdrant
    ports:
      - "6333:6333"  # Port for Qdrant service
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
