apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy-server
  template:
    metadata:
      labels:
        app: dummy-server
    spec:
      containers:
      - name: dummy-server
        image: ghcr.io/maximkartsev/prjctr-ml-in-prod-course/dummy-fastapi-server:latest
        ports:
        - containerPort: 8000
#      imagePullSecrets:
#      - name: ghcr-secret